Models/Order.cs
using System;
using System.Collections.Generic;

namespace BookStore.Models
{
    public class Order
    {
        public int Id { get; set; }
        public List<OrderItem> OrderItems { get; set; } = new();
        public int OrderTotal { get; set; }
        public DateTime OrderPlaced { get; set; }
    }
}

Controllers/OrderController.cs
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace BookStore.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly BookStoreContext _context;
        private readonly Cart _cart;

        public OrderController(BookStoreContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            var cartItems = _cart.GetAllCartItems();
            _cart.CartItems = cartItems;

            if (_cart.CartItems.Count == 0)
            {
                ModelState.AddModelError("", "Cart is empty, please add a book first.");
            }

            if (ModelState.IsValid)
            {
                CreateOrder(order);
                _cart.ClearCart();
                return View("CheckoutComplete", order);
            }

            return View(order);
        }

        public IActionResult CheckoutComplete(Order order)
        {
            return View(order);
        }
        public async Task<IActionResult> ListOrders()
        {
            var orders = await _context.Orders.ToListAsync();
            return View(orders);
        }
        public async Task<IActionResult> Details(int id)
        {
            var order = await _context.Orders
                .Include(o => o.OrderItems)
                .ThenInclude(oi => oi.Book)
                .FirstOrDefaultAsync(o => o.Id == id);

            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        public async Task<IActionResult> DeleteOrder(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }

            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(ListOrders));
        }

        public void CreateOrder(Order order)
        {
            order.OrderPlaced = DateTime.Now;

            var cartItems = _cart.CartItems;

            foreach (var item in cartItems)
            {
                var orderItem = new OrderItem()
                {
                    Quantity = item.Quantity,
                    BookId = item.Book.Id,
                    OrderId = order.Id,
                    Price = item.Book.Price * item.Quantity
                };
                order.OrderItems.Add(orderItem);
                order.OrderTotal += orderItem.Price;
            }
            _context.Orders.Add(order);
            _context.SaveChanges();
        }
    }
}

Controllers/StoreController.cs
using BookStore.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    [AllowAnonymous]
    public class StoreController : Controller
    {
        private readonly BookStoreContext _context;

        public StoreController(BookStoreContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string searchString, string minPrice, string maxPrice)
        {
            var books = _context.Book.Select(b => b);

            if (!string.IsNullOrEmpty(searchString))
            {
                books = books.Where(b => b.Title.Contains(searchString) || b.Author.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(minPrice))
            {
                var min = int.Parse(minPrice);
                books = books.Where(b => b.Price >= min);
            }

            if (!string.IsNullOrEmpty(maxPrice))
            {
                var max = int.Parse(maxPrice);
                books = books.Where(b => b.Price <= max);
            }

            return View(await books.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
    }
}

Views/Order/Checkout.cshtml
@model Order

<form asp-action="Checkout" method="post" class="form-horizontal" role="form">
    <h4>Please confirm your purchase</h4>
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Complete Order" />
        </div>
    </div>
</form>

Views/Order/CheckoutComplete.cshtml
@model BookStore.Models.Order

<h1>Thank you for your order!</h1>

<h5 class="mt-5">Order Id: @Model.Id</h5>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Book</th>
                <th>Price</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.OrderItems)
            {
                var itemTotal = item.Book.Price * item.Quantity;
                <tr>
                    <td>
                        <a class="a-cleanup" asp-controller="Store" asp-action="Details" asp-route-id="@item.Id"><img src="@item.Book.ImageUrl" style="height: 4em"></a>
                    </td>
                    <td>
                        <a class="a-cleanup" asp-controller="Store" asp-action="Details" asp-route-id="@item.Id">@item.Book.Title</a>
                    </td>
                    <td>
                        @itemTotal.ToString("c")
                    </td>
                    <td>
                        @item.Quantity
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <td></td>
            <td class="text-right">
                <strong>Total:</strong>
            </td>
            <td>
                <strong>@Model?.OrderTotal.ToString("c")</strong>
            </td>
            <td></td>
        </tfoot>
    </table>

Views/Order/Details.cshtml
@model BookStore.Models.Order
@using BookStore.Helpers

<h1>Order Details</h1>

<h5 class="mt-5">Order Id: @Model.Id</h5>

<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>Book</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Item Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderItems)
        {
                <tr>
                    <td>
                    @if (item.Book != null)
                    {
                                <a class="a-cleanup" asp-controller="Store" asp-action="Details" asp-route-id="@item.BookId"><img src="@item.Book.ImageUrl" style="height: 4em"></a>
                    }
                    </td>
                    <td>
                    @if (item.Book != null)
                    {
                                <a class="a-cleanup" asp-controller="Store" asp-action="Details" asp-route-id="@item.BookId">@item.Book.Title</a>
                    }
                    else
                    {
                        @item.BookId
                    }
                    </td>
                    <td>
                    @Html.DisplayPrice(item.Price)
                    </td>
                    <td>
                    @item.Quantity
                    </td>
                    <td>
                    @Html.DisplayPrice(item.Order.OrderTotal)
                    </td>
                </tr>
        }

    </tbody>
    <tfoot>
        <tr>
            <td></td>
            <td class="text-right">
                <strong>Total:</strong>
            </td>
            <td colspan="2"></td>
            <td>
                <strong>@Html.DisplayPrice(Model.OrderTotal)</strong>
            </td>
        </tr>
    </tfoot>
                   <a asp-action="DeleteOrder" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>
</table>

Views/Order/ListOrders.cshtml
@model IEnumerable<BookStore.Models.Order>
@using BookStore.Helpers

<h1>Orders</h1>

<table class="table">
    <thead>
        <tr>
            <th>Order ID</th>
            <th>Order Date</th>
            <th>Order Total</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
                    <tr>
                        <td>@order.Id</td>
                        <td>@order.OrderPlaced.ToString("yyyy-MM-dd HH:mm:ss")</td>
                        <td>@Html.DisplayPrice(order.OrderTotal)</td>
                        <td>
                            <a asp-action="Details" asp-route-id="@order.Id" class="btn btn-primary">View</a>
                            <a asp-action="DeleteOrder" asp-route-id="@order.Id" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
        }
    </tbody>
</table>